pluginManagement {
	repositories {
		maven {
			url = "https://repo.sleeping.town"
			content {
				includeGroup "agency.highlysuspect"
				includeGroup "agency.highlysuspect.minivan" //this is a certified plugins dsl moment
			}
		}
		gradlePluginPortal()
		maven { url = "https://maven.fabricmc.net/" }
		maven { url = "https://repo.spongepowered.org/repository/maven-public/" }
	}
}

//i love toolchains im toolchaining out rn
plugins {
	id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

enableFeaturePreview "STABLE_CONFIGURATION_CACHE"

rootProject.name = "mods"

include(
	"vanilla",
	"floader-only",
	
	"neo-1.21.5",
	"fabric-1.21.5",
	
//	"neo-1.21.1",
	"fabric-1.21.1",
	
	"fabric-1.20.1",
	"forge-1.20.1",
)