plugins {
	id "java"
}

evaluationDependsOn(":vanilla")

repositories {
	maven {
		url = "https://maven.fabricmc.net/"
		content {
			includeGroup "net.fabricmc"
		}
	}
}

dependencies {
	implementation "net.fabricmc:fabric-loader:${project.floaderVersion}"
	implementation project(path: ":vanilla", configuration: "modAnyVersionAnyElements")
}

configurations {
	consumable("floaderOnlyElements")
}

artifacts {
	floaderOnlyElements tasks.jar
}