plugins {
	id "java"
	id "agency.highlysuspect.minivan" version "0.5"
	id "maven-publish"
}

repositories {
	maven {
		url = "https://repo.spongepowered.org/repository/maven-public/"
		content {
			includeGroup "org.spongepowered"
		}
	}
}

//TODO: maybe four layers of configurations here
// modAnyVersionAny
// modAnyVersion1_21_1
// modTestmodVersionAny
// modTestmodVersion1_21_1

//argument "1.21.1" returns the source set "minecraft1_21_1"
def minecraftSourceSet(String v) {
	return project.sourceSets.maybeCreate("minecraft${v.replace('.', '_')}")
}

def setupMc(String v) {
	println "vanilla ${v}"
	
	//make a source set for this minecraft version
	def set = minecraftSourceSet(v)
	String setImpl = set.implementationConfigurationName //wordy
	
	//inherit from main source set (contains code shared across all vanilla versions)
	set.compileClasspath += sourceSets.main.compileClasspath
	set.runtimeClasspath += sourceSets.main.runtimeClasspath
	project.dependencies.add(setImpl, sourceSets.main.output)
	
	//add minecraft and its dependencies to this source set
	def mc = minivan.minecraftBuilder().version(v).build().getMinecraft() //fabric style ATs can go in there too...
	mc.installTo(project, setImpl)
	project.dependencies.add(setImpl, "com.mojang:logging:1.1.1") //TODO, why isn't this one showing up? minivan bug?
	project.dependencies.add(setImpl, "org.spongepowered:mixin:0.8.5") //not vanilla but might as well
	project.dependencies.add(setImpl, "org.jetbrains:annotations:16.0.2") //ditto
	
	//do variable expansion in processResources
	tasks.named(set.getProcessResourcesTaskName()) {
		inputs.property "minecraftversion", v
		filesMatching(["**/*.json", "**/*.toml", "**/*.properties"]) {
			expand "minecraftversion": v
		}
	}
	
	//jar should include stuff from both the main and per-version source set
	//name like "minecraft1_21_1Jar"
	def jar = tasks.register(set.getJarTaskName(), Jar) {
		from set.output
		from sourceSets.main.output
		
		archiveClassifier = set.name
		destinationDirectory = tasks.jar.destinationDirectory
	}
	tasks.named("jar") { dependsOn jar }
	
	//make a configuration and put the finished jar inside it, for consuming from other projects
	//name like "minecraft1_21_1ApiElements"
	Configuration myApiElements = configurations.consumable(set.getApiElementsConfigurationName()).get()
	project.artifacts.add(myApiElements.name, jar)
}

def setupMod(String mod, String... mcVersions) {
	println "mod ${mod} for ${Arrays.toString(mcVersions)}"
	
	//source-set for code intended to be shared across all versions of the mod
	def allVersionSet = sourceSets.create(mod)
	
	//inherit from main source set
	allVersionSet.compileClasspath += sourceSets.main.compileClasspath
	allVersionSet.runtimeClasspath += sourceSets.main.runtimeClasspath
	project.dependencies.add(allVersionSet.implementationConfigurationName, sourceSets.main.output)
	
	//for each minecraft version used by this mod...
	for(String v : mcVersions) {
		def verSet = sourceSets.create(mod + v.replace('.', '_'))
		
		//inherit from the all-version set
		verSet.compileClasspath += allVersionSet.compileClasspath
		verSet.runtimeClasspath += allVersionSet.runtimeClasspath
		project.dependencies.add(verSet.implementationConfigurationName, allVersionSet.output)
		
		//inherit from the vanilla minecraft set
		def minecraftSet = minecraftSourceSet(v)
		verSet.compileClasspath += minecraftSet.compileClasspath
		verSet.runtimeClasspath += minecraftSet.runtimeClasspath
		project.dependencies.add(verSet.implementationConfigurationName, minecraftSet.output)
		
		//jar should include stuff from both the main and per-version source set without shading
		def captureLmao = new String(v)
		def jar = tasks.register(verSet.getJarTaskName(), Jar) {
			group "build"
			from sourceSets.main.output //everything shared //TODO shade this
			from minecraftSet.output //shared across all mods on this version of minecraft //TODO shade this
			from allVersionSet.output //shared across all minecraft versions of mod
			from verSet.output //specific to this mod/version pair
			
			archiveBaseName = "${mod}-${captureLmao}" // "testmod-1.20.1"
			destinationDirectory = tasks.jar.destinationDirectory
		}
		tasks.named("jar") { dependsOn jar }
		
		tasks.named(verSet.getProcessResourcesTaskName()) {
			inputs.property "minecraftversion", v
			filesMatching(["**/*.json", "**/*.toml", "**/*.properties"]) {
				expand "minecraftversion": v
			}
		}
		
		//make a configuration and put the finished jar inside it, for consuming from other projects
		//name like "testmod1_21_1ApiElements"
		Configuration myApiElements = configurations.consumable(verSet.getApiElementsConfigurationName()).get()
		project.artifacts.add(myApiElements.name, jar)
		
		//a "Run config", not a full minecraft launcher but at least it's on the classpath
		//name like "simpleRunTestmod1_21_1"
		tasks.register(verSet.getTaskName("simpleRun", ""), JavaExec) {
			group("simpleRun")
			
//			mainClass = "agency.highlysuspect.mods.test.Hi" //TODO
			classpath = verSet.runtimeClasspath
			
			// ./run/testmod/1.20.1/
			workingDir = project.layout.projectDirectory.asFile.toPath()
				.resolve("run").resolve(mod).resolve(v).toFile()
			doFirst { workingDir.mkdirs() }
		}
	}
}

setupMc("1.20.1")
setupMc("1.21.1")

setupMod("testmod", "1.20.1", "1.21.1")
setupMod("testmod2", "1.20.1", "1.21.1")