plugins {
	id "java"
	id "agency.highlysuspect.minivan" version "0.5"
	id "maven-publish"
}

repositories {
	maven {
		url = "https://repo.spongepowered.org/repository/maven-public/"
		content {
			includeGroup "org.spongepowered"
		}
	}
}

def setupMc(String v) {
	println "vanilla ${v}"
	
	//grab vanilla jar and libraries using minivan
	def mc = minivan.minecraftBuilder().version(v).build().getMinecraft() //fabric style ATs can go in there too...
	
	//make a source set for this minecraft version
	def set = sourceSets.create("minecraft${v.replace('.', '_')}") //like "minecraft1_21_1"
	String setImpl = set.implementationConfigurationName //wordy
	
	//inherit from main source set (contains code shared across all vanilla versions)
	set.compileClasspath += sourceSets.main.compileClasspath
	set.runtimeClasspath += sourceSets.main.runtimeClasspath
	project.dependencies.add(setImpl, sourceSets.main.output)
	
	//add minecraft and its dependencies to this per-version source set
	mc.installTo(project, setImpl)
	project.dependencies.add(setImpl, "com.mojang:logging:1.1.1") //TODO, why isn't this one showing up? minivan bug?
	project.dependencies.add(setImpl, "org.spongepowered:mixin:0.8.5") //not vanilla but might as well
	project.dependencies.add(setImpl, "org.jetbrains:annotations:16.0.2") //ditto
	
	//do variable expansion in processResources
	tasks.named(set.getProcessResourcesTaskName()) {
		inputs.property "minecraftversion", v
		
		filesMatching(["**/*.json", "**/*.toml", "**/*.properties"]) {
			expand "minecraftversion": v
		}
	}
	
	//jar should include stuff from both the main and per-version source set
	def jar = tasks.register(set.getJarTaskName(), Jar) {
		from set.output
		from sourceSets.main.output
		
		archiveClassifier = set.name
		destinationDirectory = tasks.jar.destinationDirectory
	}
	tasks.named("jar") { dependsOn jar }
	
	//make a configuration and put the finished jar inside it, for consuming from other projects
	Configuration myApiElements = configurations.consumable(set.getApiElementsConfigurationName()).get()
	project.artifacts.add(myApiElements.name, jar)
	
	//a "Run config", not a full minecraft launcher but at least it's on the classpath
	tasks.register(set.getTaskName("simpleRun", ""), JavaExec) {
		group("simpleRun")
		
		mainClass = "agency.highlysuspect.mods.test.Hi"
		classpath = set.runtimeClasspath
		
		workingDir = new File(new File(project.layout.projectDirectory.asFile, "run"), v) // ./run/1.20.1/
		doFirst {
			workingDir.mkdirs()
		}
	}
}

setupMc("1.20.1")
setupMc("1.21.1")
