modLoader = "javafml"
loaderVersion = "[1,)"
license = "${license}"
issueTrackerURL = "${issues}"
logoFile = "${modid}_icon.png"

[[mods]]
modId = "${modid}"
version = "${version}"
displayName = "${name}"
description = "Adds a keybind to options for the narrator."
authors = "${author}"

[[mixins]]
config = "rebind_narrator.mixins.json"