plugins {
	id "java"
	id "net.neoforged.moddev" version "2.0.95" // https://projects.neoforged.net/neoforged/ModDevGradle
}

//archivesBaseName = "${rootProject.name}-neo-1.21.1"

evaluationDependsOn(":vanilla") //reaching across sourceSets

configurations {
	modAnyVersionAnyShade
	modAnyVersion1_21_1Shade
	
	implementation.extendsFrom modAnyVersionAnyShade
	implementation.extendsFrom modAnyVersion1_21_1Shade
}

//MAIN SOURCESET contains vanilla for every version, vanilla for this version, and (added by MDG) a copy of neoforge
dependencies {
	modAnyVersionAnyShade project(path: ":vanilla", configuration: "modAnyVersionAnyElements")
	modAnyVersion1_21_1Shade project(path: ":vanilla", configuration: "modAnyVersion1_21_1Elements")
}

neoForge {
	version "21.5.75" // https://projects.neoforged.net/neoforged/neoforge
	
	runs {
		client {
			client()
		}
	}
}

def makeMod2(String mod) {
	println "makeMod2 mod ${mod}"
	
	SourceSet set = sourceSets.create("mod${mod.capitalize()}Version1_21_1LoaderNeoforge")
	
	//inherit from main sourceset (which contains neoforge and code shared across neo 1.21 mods)
	set.compileClasspath += sourceSets.main.compileClasspath
	set.runtimeClasspath += sourceSets.main.runtimeClasspath
	project.dependencies.add(set.implementationConfigurationName, sourceSets.main.output)
	
	//inherit from the relevant :vanilla projects
	Configuration modAnyVersionAnyShade = configurations.named("modAnyVersionAnyShade").get() //dep already created above
	Configuration modAnyVersionThisShade = configurations.named("modAnyVersion1_21_1Shade").get() //above
	
	Configuration modThisVersionAnyShade = configurations.create("mod${mod.capitalize()}VersionAnyVanilla")
	Dependency modThisVanillaAnyDep = dependencies.project(path: ":vanilla", configuration: "mod${mod.capitalize()}VersionAnyElements")
	project.dependencies.add(modThisVersionAnyShade.name, modThisVanillaAnyDep)
	
	Configuration modThisVersionThisShade = configurations.create("mod${mod.capitalize()}Version1_21_1Vanilla")
	Dependency modThisVanillaThisDep = dependencies.project(path: ":vanilla", configuration: "mod${mod.capitalize()}Version1_21_1Elements")
	project.dependencies.add(modThisVersionThisShade.name, modThisVanillaThisDep)
	
	configurations.named(set.implementationConfigurationName) {
		it.withDependencies {
			it.add project.dependencies.create(modAnyVersionAnyShade)
			it.add project.dependencies.create(modAnyVersionThisShade)
			it.add project.dependencies.create(modThisVersionAnyShade)
			it.add project.dependencies.create(modThisVersionThisShade)
		}
	}
	
	//thinjar
	def thinJar = tasks.register("mod${mod.capitalize()}Version1_21_1LoaderNeoforgeThinJar", Jar) {
		from set.output
		archiveBaseName = "${mod}-1.21.1-neoforge-thin"
		destinationDirectory = tasks.jar.destinationDirectory
	}
	tasks.named("jar") { dependsOn thinJar }
	
	//fatjar
	def fatJar = tasks.register("mod${mod.capitalize()}Version1_21_1LoaderNeoforgeFatJar", Jar) {
		from set.output
		from sourceSets.main.output //TODO shade
		from modAnyVersionAnyShade.collect { zipTree it } //TODO shade
		from modAnyVersionThisShade.collect { zipTree it } //TODO shade
		from modThisVersionAnyShade.collect { zipTree it } //TODO shade
		from modThisVersionThisShade.collect { zipTree it } //TODO shade
		
		archiveBaseName = "${mod}-1.21.1-neoforge"
		destinationDirectory = tasks.jar.destinationDirectory
	}
	tasks.named("jar") { dependsOn fatJar }
	
	//neoforge run
	neoForge {
		mods {
			"${mod}" {
				sourceSet set
				sourceSet project(":vanilla").sourceSets["mod${mod.capitalize()}Version1_21_1"]
				sourceSet project(":vanilla").sourceSets["mod${mod.capitalize()}VersionAny"]
				
				//FOLLOWING SOURCE-SETS CRASH DUE TO SPLIT PACKAGES IF THERES MORE THAN ONE MOD
				//will need to shade!!!!
				sourceSet sourceSets.main
				sourceSet project(":vanilla").sourceSets["modAnyVersion1_21_1"]
				sourceSet project(":vanilla").sourceSets["modAnyVersionAny"]
			}
		}
	}
}

makeMod2("testmod")
//makeMod2("testmod2")
