plugins {
	id "java"
}

evaluationDependsOn(":ap-testing")

dependencies {
	annotationProcessor project(path: ":ap-testing", configuration: "runtimeElements")
}

tasks.withType(JavaCompile).configureEach {
	//it.options.verbose = true
}

project.afterEvaluate {
	//logger.lifecycle("ASHJKDASHJKDASJKDOOOOOOOOOOOOOOOOOOOOOOOOO");
	//logger.lifecycle(project(":ap-testing").tasks.jar.outputs.getFiles().iterator().next().toString());
	//logger.lifecycle(sourceSets.main.output.classesDirs.iterator().next().toString());
}

tasks.register("aaa_potato", JavaCompile) {
	group "build"
	outputs.upToDateWhen { false }
	
	it.classpath = sourceSets.main.output.classesDirs
	println("classesDirs:")
	println(sourceSets.main.output.classesDirs);
	
	it.options.compilerArgs = [
					"-proc:only",
					"-verbose"
	]
	
	it.options.annotationProcessorPath = project(":ap-testing").tasks.jar.outputs.getFiles()
	
	File dest = project.layout.buildDirectory.dir("foobar").get().asFile
	dest.mkdirs()
	it.destinationDirectory = dest
	
	doFirst {
		logger.lifecycle(String.join("\n", options.allCompilerArgs))
	}
}