plugins {
	id "java"
	id "application"
}

application {
	mainClass = "uploaderthing.Uploader"
}

repositories {
	mavenCentral()
}

dependencies {
	implementation "com.google.code.gson:gson:2.13.1"
	
	//for the oauth redirect url
	implementation "org.eclipse.jetty:jetty-server:12.1.1"
	
	//java's httpclient kinda sucks
	implementation "com.github.mizosoft.methanol:methanol:1.8.3"
}

tasks.withType(JavaExec).configureEach {
	it.standardInput = System.in
	it.environment("COLLECT_DIR", new File(project.rootDir, "collect").getAbsolutePath())
	it.environment("SECRETS_TXT", new File(project.rootDir, "secrets.txt").getAbsolutePath())
}