plugins {
	id "java-gradle-plugin"
}

repositories {
	maven {
		url = "https://repo.sleeping.town"
		content {
			includeGroup "agency.highlysuspect"
			includeGroup "agency.highlysuspect.minivan" //this is a certified plugins dsl moment
		}
	}
	gradlePluginPortal()
	maven {url = "https://maven.fabricmc.net/"}
	maven {url = "https://repo.spongepowered.org/repository/maven-public/"}
}

dependencies {
	// https://maven.fabricmc.net/fabric-loom/fabric-loom.gradle.plugin/
	implementation "fabric-loom:fabric-loom.gradle.plugin:1.11.5"
	
	// https://projects.neoforged.net/neoforged/ModDevGradle
	def mdgVersion = "2.0.95"
	implementation "net.neoforged.moddev:net.neoforged.moddev.gradle.plugin:${mdgVersion}"
	implementation "net.neoforged.moddev.legacyforge:net.neoforged.moddev.legacyforge.gradle.plugin:${mdgVersion}"
	
	// https://github.com/CrackedPolishedBlackstoneBricksMC/minivan/releases
	implementation "agency.highlysuspect.minivan:agency.highlysuspect.minivan.gradle.plugin:0.5"
	
	// https://github.com/unascribed/FlexVer/tree/trunk/java
	implementation "com.unascribed:flexver-java:1.1.1"

    // https://mvnrepository.com/artifact/com.google.code.gson/gson
    implementation "com.google.code.gson:gson:2.13.1"
}

gradlePlugin {
	plugins {
		"mod-setup-fabric" {
			id = "mod-setup-fabric"
			implementationClass = "agency.highlysuspect.modsetup.AbstractLoaderSetupPlugin\$FabricSetupPlugin"
		}
		"mod-setup-neoforge" {
			id = "mod-setup-neoforge"
			implementationClass = "agency.highlysuspect.modsetup.AbstractLoaderSetupPlugin\$NeoforgeSetupPlugin"
		}
		"mod-setup-forge-via-mdg" {
			id = "mod-setup-forge-via-mdg"
			implementationClass = "agency.highlysuspect.modsetup.AbstractLoaderSetupPlugin\$ForgeViaMdgSetupPlugin"
		}
		"vanilla-setup" {
			id = "vanilla-setup"
			implementationClass = "agency.highlysuspect.modsetup.VanillaSetupPlugin"
		}
	}
}