modLoader = "javafml"
loaderVersion = "[1,)"
license = "LGPL-3.0-or-later"
issueTrackerURL = "https://github.com/quat1024/RebindNarrator/issues"
logoFile = "rebindnarratoricon.png"

[[mods]]
modId = "quatlib"
version = "0"
displayName = "quatlib"
description = "Probably should not be published!"
authors = "quaternary"
credits = "Your mom"

#[[mixins]]
#config = "rebind_narrator.mixins.json"