modLoader = "javafml"
loaderVersion = "[1,)"
license = "LGPL-3.0-or-later"
issueTrackerURL = "https://github.com/quat1024/RebindNarrator/issues"
#logoFile = "rebindnarratoricon.png"

[[mods]]
modId = "modder_name_lib"
version = "0"
displayName = "ModderNameLib"
description = "ModderNameLib"
authors = "quaternary"
credits = "Your mom"

#[[mixins]]
#config = "rebind_narrator.mixins.json"